on:
  push:
    branches:
      - main

jobs:
  publish-extension:
    runs-on: ubuntu-latest
    steps:
      - name: Publish extension
        id: publisher
        uses: sigma/vsce-publish-action@v0.0.2
        with:
          vsce_token: ${{ secrets.VSCE_TOKEN }}
          build_pkg: yes
      - name: Process further
        run: echo ${{ steps.publisher.outputs.vsix_path }}
